### ISSUE TITLE
Fix building on other POSIX OSs

### ISSUE THREAD

**Issue by brad0** [mariadb-corporation/libmarias3#88]
I noticed there was a commit recently to fix building on FreeBSD. The issue affects other POSIX OS's as well (I'm on OpenBSD).

The header in question is a POSIX header and should just be included the same as the others. Here is patch to adjust the code as so.

https://comstyle.com/mariadb/libmarias3-marias3.diff

**Comment by LinuxJedi** [comment]
Ah! I did wonder which POSIX OSs also have this issue. Can you please open a PR for this?

**Comment by brad0** [comment]
By PR you're referring to JIRA?

**Comment by LinuxJedi** [comment]
Pull Request, in GitHub

**Comment by brad0** [comment]
Ah, overload of acronyms (Problem Report). I've been looking at doing a PR as well before opening the issue, never having done it before, and this looks overly complicated.

**Comment by LinuxJedi** [comment]
I have created a Jira ticket to track this: https://jira.mariadb.org/browse/MDEV-23377

Someone else will take over this as this is my last day at MariaDB.

**Comment by brad0** [comment]
ping ping ping ping ping ping ping ping ping.

**Comment by drrtuy** [comment]
@brad0 I'll test you patch with facilities that uses this lib to proceed wth merging.

**Comment by brad0** [comment]
Thanks, commit 479231a985490f0ff3a8c8725f1d87ea5b0d9af0 that went in has resolved the issue.

**Comment by drrtuy** [comment]
Closing this then.
